add swagger dependency
ggazila/review-analysis pull request #1
Opened 2020-03-01 19:42 UTC by ggazila

add jackson-dataformat-csv
add entities
add some repository implementations

2020-03-02 09:50 UTC, boroda4436 requested changes

2020-03-02 09:50 UTC, boroda4436 commented on src/main/java/mate/academy/review/analysis/entity/Product.java
> +    private String productId;
@ggazila what is the difference between id and productId? Is the productId unique?

2020-03-02 09:50 UTC, boroda4436 commented on src/main/java/mate/academy/review/analysis/repository/ProfileRepository.java
> +public interface ProfileRepository {
@ggazila consider adding two more repositories for product and review

2020-03-05 09:18 UTC, Tarabarnik approved these changes

2020-03-05 13:43 UTC, merged